version: '3.8'

services:
  db:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata: